export const googleQuestions = [
  { question: "How do you find the longest path in a directed acyclic graph (DAG)?", answer: "Solve in O(V + E) time using Topological Sorting. Initialize distance array to negative infinity, set start source to 0, and relax edges in topological order.", category: "Coding" },
  { question: "What is the difference between TCP and UDP?", answer: "TCP is connection-oriented, reliable, packet-ordered, and controls congestion. UDP is connectionless, fast, unreliable, and has no flow overhead.", category: "Technical" },
  { question: "Design a URL shortening service like TinyURL.", answer: "Use a relational or key-value store. Map base-10 auto-increment IDs to base-62 encoding (0-9, a-z, A-Z) to generate 7-character aliases. Implement Redis cache layer.", category: "Technical" },
  { question: "How does consistent hashing work?", answer: "Consistent hashing maps nodes and keys to a virtual ring. When a node joins or leaves, only K/N keys need remapping, preventing database wide invalidations.", category: "Technical" },
  { question: "What is a Trie data structure and its time complexity for lookup?", answer: "A Trie (prefix tree) stores character sequences. Retrieval is O(L) where L is string length, making prefix searches faster than hash maps.", category: "Coding" },
  { question: "Explain the A* search algorithm.", answer: "A* finds the shortest path using f(n) = g(n) + h(n), where g(n) is actual cost from start and h(n) is heuristic estimate to target.", category: "Technical" },
  { question: "What is MapReduce and how does it scale?", answer: "MapReduce processes datasets in parallel. Map filters/groups records, Shuffle redistributes them, and Reduce aggregates outputs.", category: "Technical" },
  { question: "What is garbage collection in Java/V8 and how does it prevent memory leaks?", answer: "GC reclaims unused heap memory using mark-and-sweep or generational collection. Avoid retains on global variables to prevent leaks.", category: "Technical" },
  { question: "Explain Big-O time complexity of QuickSort.", answer: "Average: O(N log N). Worst case: O(N^2) when pivot is always smallest/largest. Use randomized pivot selection to mitigate.", category: "Coding" },
  { question: "What are V8 engine hidden classes?", answer: "V8 dynamically maps JS objects to compiler structures (Shape/Hidden classes) to speed up properties lookups, optimizing dynamic allocations.", category: "Technical" },
  { question: "Design an autocomplete query suggestion system.", answer: "Store prefixes in a Trie. Keep top 10 frequent search terms on each node. Replicate query logs to compute frequency updates asynchronously.", category: "Technical" },
  { question: "How do you check if a binary tree is balanced?", answer: "A tree is balanced if heights of left and right subtrees differ by at most 1. Compute heights recursively and return -1 if unbalanced.", category: "Coding" },
  { question: "What is a Bloom Filter?", answer: "A space-efficient probabilistic data structure used to test set membership. Returns 'definitely not in set' or 'probably in set' with no false negatives.", category: "Technical" },
  { question: "How does the PageRank algorithm work?", answer: "Computes recursive probability distributions. A page rank depends on number and rank of external pages referencing it.", category: "Technical" },
  { question: "What is the difference between processes and threads?", answer: "A process has its own address space, memory, and resources. Threads share memory and execution context within the parent process.", category: "Technical" },
  { question: "Describe a time you handled a project with vague requirements.", answer: "Focus on stakeholder communication, building a MVP, setting early milestones, and establishing robust testing loops.", category: "HR" },
  { question: "Why do you want to work at Google?", answer: "Mention their technological impact, scale of services, emphasis on code quality, and desire to solve foundational computer science puzzles.", category: "HR" },
  { question: "Explain a time you disagreed with a technical design decision.", answer: "Explain trade-offs objectively using data/benchmarks. Align with the team's goals and respect the final consensus.", category: "HR" },
  { question: "How do you manage deadlines in a fast-paced team?", answer: "Prioritize using critical path analysis, break deliverables into micro-tasks, configure notifications, and raise risks early.", category: "HR" },
  { question: "Describe a project you are most proud of.", answer: "Quantify results: discuss the system architecture, how you reduced database latency, and placement feedback you received.", category: "HR" }
];

export const microsoftQuestions = [
  { question: "Implement a function to reverse a linked list.", answer: "Maintain prev = null, curr = head, nextNode = null. Iterate setting nextNode = curr.next, curr.next = prev, prev = curr, curr = nextNode. Set head = prev.", category: "Coding" },
  { question: "Explain Virtual Memory and Paging.", answer: "Virtual memory maps logical program spaces to physical slots. Paging splits memory into fixed pages (logical) and frames (physical) to prevent fragmentation.", category: "Technical" },
  { question: "What is a database transaction deadlock and how is it detected?", answer: "Deadlock happens when transactions hold resources the other needs. Databases resolve it using wait-for graphs and killing the cheaper transaction.", category: "Technical" },
  { question: "What are semaphores and mutexes?", answer: "Mutex is a locking mechanism for a single thread. Semaphore is a signaling variable allowing multiple threads (up to N) to access concurrent resources.", category: "Technical" },
  { question: "What are ACID properties in SQL databases?", answer: "Atomicity (all or nothing), Consistency (valid state transitions), Isolation (independent transactions), and Durability (permanent logs).", category: "Technical" },
  { question: "Explain database indexing indexes (B-Trees vs Hash).", answer: "B-Tree indexes sort keys and support range queries. Hash indexes map keys to specific buckets, offering O(1) exact lookups but no range support.", category: "Technical" },
  { question: "How do you implement a thread-safe Singleton in C# or Java?", answer: "Use double-checked locking or a static nested class initialization helper to prevent concurrent instantiations.", category: "Coding" },
  { question: "Design a parking lot management system.", answer: "Use OOP design: ParkingLot class manages Level objects containing Spot instances. Abstract Vehicle class has Car/Motorcycle extensions.", category: "Technical" },
  { question: "What is a segment tree and its use cases?", answer: "A tree structure used to perform range queries (e.g. range sum, min/max) and updates in O(log N) time, outperforming simple arrays.", category: "Coding" },
  { question: "Explain the differences between SQL normalization and denormalization.", answer: "Normalization reduces redundancies up to 3NF/BCNF. Denormalization merges tables to skip join overheads and speed up reads.", category: "Technical" },
  { question: "What is a memory leak and how do you profile it?", answer: "Memory leaks occur when objects are retained in memory after they are no longer needed. Use profilers like Chrome DevTools or VS diagnostics to trace reference trees.", category: "Technical" },
  { question: "Explain the difference between stack and heap memory.", answer: "Stack is fast, manages static allocations, and holds local variables. Heap is larger, dynamic, manages reference objects, and has GC cycles.", category: "Technical" },
  { question: "What is the purpose of DNS (Domain Name System)?", answer: "DNS acts as the phonebook of the internet, resolving human-readable domain names (e.g., microsoft.com) to machine-readable IP addresses.", category: "Technical" },
  { question: "How does binary search work on a sorted array?", answer: "Compare search element with the middle item. If equal, return index. If smaller, search left half. If larger, search right half. Time is O(log N).", category: "Coding" },
  { question: "Explain compilation vs interpretation.", answer: "Compilation translates source code directly to machine files (fast, e.g. C++). Interpretation translates code line-by-line during runtime (flexible, e.g. Python).", category: "Technical" },
  { question: "Why do you want to join the Microsoft Azure team?", answer: "Explain your interest in cloud architectures, global scale infrastructures, virtualizations, and contributing to core computing fabrics.", category: "HR" },
  { question: "How do you handle bugs in production code?", answer: "Replicate in staging, read logs to trace root causes, deploy a hotfix, write regression tests, and perform a post-mortem.", category: "HR" },
  { question: "Tell me about a time you had to learn a new framework quickly.", answer: "Detail your approach: review docs, build sandbox apps, find code templates, and ask senior developers in peer reviews.", category: "HR" },
  { question: "How do you prioritize features in a product backlog?", answer: "Use frameworks like MoSCoW (Must, Should, Could, Won't) or RICE (Reach, Impact, Confidence, Effort) to align with business requirements.", category: "HR" },
  { question: "What does teamwork mean to you?", answer: "Open communication, respecting diverse skill sets, aligning on unified milestones, and taking shared accountability for code deliveries.", category: "HR" }
];

export const amazonQuestions = [
  { question: "How would you design a parking lot system?", answer: "Apply OOP principles. Define classes like ParkingLot, Level, Spot (compact, large, handicapped), and Vehicle (Car, Bike, Truck). Use Singleton pattern.", category: "Technical" },
  { question: "What is the difference between SQL and NoSQL?", answer: "SQL is relational, schema-strict, table-based, scales vertically. NoSQL is document/key-value based, flexible schema, scales horizontally.", category: "Technical" },
  { question: "Explain the LRU (Least Recently Used) Cache design.", answer: "Use a combination of a Hash Map (for O(1) access) and a Double Linked List (for O(1) element eviction and movement).", category: "Coding" },
  { question: "What is a Hash Map collision and how is it resolved?", answer: "Collision happens when different keys yield same hash values. Resolved using Chaining (linked lists/red-black trees at node buckets) or Open Addressing.", category: "Technical" },
  { question: "Describe a time you solved a challenging technical latency issue.", answer: "Discuss how you diagnosed SQL queries or API roundtrips, set up Redis caching layers, and achieved a quantifiable speedup.", category: "HR" },
  { question: "Design an online shopping cart service.", answer: "Microservices: UserService, ProductService, CartService, OrderService. Use Redis to persist active cart states before checkout db writes.", category: "Technical" },
  { question: "What are AWS Lambda functions?", answer: "Event-driven serverless computing that runs code in containerized environments. Scales automatically and charges only for compute milliseconds.", category: "Technical" },
  { question: "Explain the difference between REST and gRPC.", answer: "REST uses HTTP/1.1 and JSON payloads (highly compatible). gRPC uses HTTP/2 and Protocol Buffers (faster binary serialization, lower bandwidth).", category: "Technical" },
  { question: "Design a notification dispatcher system.", answer: "Use a message broker (RabbitMQ/Kafka) to queue alert events, and worker pools to dispatch SMS, Emails, and Socket push alerts.", category: "Technical" },
  { question: "What is the purpose of database replication?", answer: "Replicates data to secondary servers to provide high read scalability, backup redundancy, and failover support during main db crashes.", category: "Technical" },
  { question: "Explain the Leadership Principle: Customer Obsession.", answer: "Start with the customer and work backwards. Earn and keep customer trust, and make decisions centered on customer value over short-term metrics.", category: "HR" },
  { question: "Explain the Leadership Principle: Ownership.", answer: "Take long-term accountability. Never say 'that's not my job.' Act on behalf of the entire company, not just your own small team.", category: "HR" },
  { question: "Explain the Leadership Principle: Bias for Action.", answer: "Speed matters in business. Many decisions are reversible and don't need extensive studies. Value calculated risk-taking.", category: "HR" },
  { question: "What is the difference between monolithic and microservices architecture?", answer: "Monolith compiles all logic into one deployable unit (simple). Microservices partition features into independent APIs (decoupled, scalable).", category: "Technical" },
  { question: "How does the OAuth 2.0 authorization code flow work?", answer: "User logs in, receives auth code from provider. Client backend exchanges the code for access/ID token to secure user sessions.", category: "Technical" },
  { question: "What is rate limiting and how do you implement it?", answer: "Prevents API abuse. Implement token bucket or sliding window algorithms using Redis to track client requests per IP.", category: "Technical" },
  { question: "What is CD/CI pipeline?", answer: "Continuous Integration automates testing code updates. Continuous Deployment automates deploying validated code bundles directly to cloud servers.", category: "Technical" },
  { question: "How do you ensure data integrity in asynchronous microservices?", answer: "Use event sourcing or the Saga pattern to handle distributed transactions and execute compensating actions if steps fail.", category: "Technical" },
  { question: "Tell me about a time you had to deliver results under pressure.", answer: "Discuss how you prioritized tasks, automated manual configurations, communicated updates, and delivered quality SDE outputs.", category: "HR" },
  { question: "Why Amazon?", answer: "Highlight their leadership principles, SDE ownership culture, massive scale of AWS, and opportunities to build systems that touch millions.", category: "HR" }
];

export const tcsQuestions = [
  { question: "What is the difference between primary key and unique key in SQL?", answer: "A primary key uniquely identifies each record and cannot contain NULL. A unique key also uniquely identifies but allows a single NULL.", category: "Technical" },
  { question: "Explain the pillars of Object Oriented Programming.", answer: "Abstraction (hides complexity), Encapsulation (secures data), Inheritance (reuses code), and Polymorphism (handles dynamic method bindings).", category: "Technical" },
  { question: "Why do you want to work with TCS?", answer: "Mention TCS is a global leader in IT delivery. Discuss its career growth training models (TCS iON), stability, and massive global client base.", category: "HR" },
  { question: "What is the difference between Java's abstract class and interface?", answer: "Abstract class can have state and concrete methods. Interface (pre-Java 8) only has abstract methods. Class extends one class, implements multiple interfaces.", category: "Technical" },
  { question: "Explain SQL Joins and their types.", answer: "Inner Join (matching keys), Left Join (all left, matching right), Right Join (all right, matching left), and Full Outer Join (all rows).", category: "Technical" },
  { question: "What is garbage collection in Java?", answer: "The JVM automatically destroys objects that are no longer referenced in memory, freeing up heap allocation spaces.", category: "Technical" },
  { question: "What is the difference between array and arraylist?", answer: "Array is static (fixed size, stores primitives or objects). ArrayList is dynamic (growable size, stores objects, supports utility API methods).", category: "Technical" },
  { question: "What is a software bug and testing lifecycle?", answer: "A bug is logical/syntax error. Testing lifecycle includes Requirement, Planning, TestCase Dev, Execution, Bug Reporting, and Closure.", category: "Technical" },
  { question: "Explain method overloading vs method overriding.", answer: "Overloading: same name, different signatures in same class. Overriding: same name, same signature in parent/child classes.", category: "Technical" },
  { question: "What is a DBMS and why is it preferred over file systems?", answer: "DBMS provides data consistency, prevents redundancy, secures credentials, supports transactions, and handles complex queries easily.", category: "Technical" },
  { question: "What is the main function in C/Java and its arguments?", answer: "Main is execution entrypoint. In Java: 'public static void main(String[] args)' accepts command line arguments as string array.", category: "Technical" },
  { question: "What is exception handling and try-catch-finally?", answer: "Secures code from crash. Try contains risky code, Catch resolves exceptions, and Finally runs cleanup instructions (closes db/files) always.", category: "Technical" },
  { question: "Explain the difference between HTML and CSS.", answer: "HTML provides structure and semantic layout elements. CSS style sheets define the visuals, colors, alignments, and responsiveness.", category: "Technical" },
  { question: "What is SDLC Waterfall model?", answer: "A sequential model containing requirements, design, implementation, testing, and maintenance. Hard to make changes once a phase is complete.", category: "Technical" },
  { question: "What is Cloud Computing?", answer: "On-demand delivery of compute power, storage, and database services over the internet with pay-as-you-go pricing.", category: "Technical" },
  { question: "Describe a project you worked on during college.", answer: "Explain the tech stack, problem solved, DB schema, and what you learned during development.", category: "HR" },
  { question: "How do you handle work-life balance?", answer: "Prioritize scheduling, set boundaries, communicate timelines, and focus on physical health and hobbies.", category: "HR" },
  { question: "Explain the difference between local and global variables.", answer: "Local variables are declared inside functions/blocks and accessible only there. Global variables are accessible throughout the script file.", category: "Technical" },
  { question: "What is an SDE intern expected to deliver?", answer: "Write readable code, participate in standups, implement test coverage, and show eagerness to learn system architectures.", category: "HR" },
  { question: "How do you feel about working in relocatable locations?", answer: "Express adaptability to work in corporate hubs (e.g. Bangalore, Pune, Chennai) to accelerate your career growth.", category: "HR" }
];

export const infosysQuestions = [
  { question: "Explain method overloading vs overriding in Java.", answer: "Overloading has same name but different signatures (compile-time). Overriding has same name and signature in parent-child classes (runtime).", category: "Technical" },
  { question: "What are the different phases of SDLC?", answer: "SDLC phases include Requirement Analysis, Planning, System Design, Software Development, Testing, Deployment, and post-release Maintenance.", category: "Technical" },
  { question: "How do you handle conflict in a development team?", answer: "Address issues objectively using metrics/trade-offs, communicate clearly, and align with client project objectives.", category: "HR" },
  { question: "What is the difference between List and Set in Java collections?", answer: "List is an ordered collection that allows duplicates. Set is an unordered collection that prohibits duplicate entries.", category: "Technical" },
  { question: "Explain the MVC (Model View Controller) architecture.", answer: "Model manages data/database logic, View renders UI layouts, and Controller processes user input and updates Model/View.", category: "Technical" },
  { question: "What is a relational database management system (RDBMS)?", answer: "A database system based on relational models where data is stored in tables (rows/columns) with defined foreign key relationships.", category: "Technical" },
  { question: "What is an API (Application Programming Interface)?", answer: "A set of protocols that allow different software systems to communicate and exchange data (e.g., frontend fetching from backend).", category: "Technical" },
  { question: "What is the difference between GET and POST requests?", answer: "GET requests data from a resource (parameters in URL, cacheable). POST submits data to be processed (parameters in body, secure).", category: "Technical" },
  { question: "Explain the concept of inheritance.", answer: "Enables a child class to inherit fields and methods from a parent class, facilitating code reusability and polymorphism.", category: "Technical" },
  { question: "What is a primary key?", answer: "A column (or set of columns) that uniquely identifies each row in a database table. Cannot contain NULL values.", category: "Technical" },
  { question: "What are the OSI layers in networks?", answer: "7 layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application. Handles end-to-end data transfers.", category: "Technical" },
  { question: "What is the difference between client-side and server-side scripting?", answer: "Client-side scripts run in the browser (HTML/CSS/JS). Server-side scripts run on backend servers (Node.js/Python/Java).", category: "Technical" },
  { question: "What is software testing?", answer: "The process of verifying software matches technical specifications and runs without logic crashes or security vulnerabilities.", category: "Technical" },
  { question: "What is a SQL schema?", answer: "The structural definition of database tables, column types, constraints, indexes, and relationships.", category: "Technical" },
  { question: "How do you define a function in Python?", answer: "Use the 'def' keyword, followed by the function name, parameters, a colon, and indented block code.", category: "Technical" },
  { question: "Why do you want to join Infosys?", answer: "Highlight its global training campuses, focus on digital transformations, employee support systems, and diverse placement opportunities.", category: "HR" },
  { question: "How do you prepare for an interview?", answer: "Review DSA basics, solve practice terminal codes, study company guides, and practice answers to behavioral HR prompts.", category: "HR" },
  { question: "Explain a time you solved a coding problem under pressure.", answer: "Explain how you isolated the bug using logs, verified the syntax, and deployed a working solution.", category: "HR" },
  { question: "What are your strengths?", answer: "Adaptability, strong conceptual coding foundations, quick framework learning, and cooperative team communication.", category: "HR" },
  { question: "Describe your college final year project.", answer: "Explain the architecture, DB schema, API integrations, and SDE project deliverables.", category: "HR" }
];

export const accentureQuestions = [
  { question: "What is database normalization and why is it used?", answer: "Organizing database tables to reduce redundancy and dependency. It splits tables and maps relationships up to 3NF.", category: "Technical" },
  { question: "What is Agile methodology and Sprint planning?", answer: "An iterative SDE approach focusing on collaboration, rapid feedback, and breaking projects into 2-4 week sprint cycles.", category: "Technical" },
  { question: "Where do you see yourself in 5 years?", answer: "Growing technically, mastering cloud frameworks, taking system architecture ownership, and leading software SDE teams.", category: "HR" },
  { question: "Explain 1NF, 2NF, and 3NF.", answer: "1NF: Atomic values. 2NF: In 1NF and no partial dependencies. 3NF: In 2NF and no transitive dependencies on primary keys.", category: "Technical" },
  { question: "What is the difference between verification and validation in software testing?", answer: "Verification checks if software matches specifications (e.g. reviews). Validation checks if software fits user expectations (e.g. E2E tests).", category: "Technical" },
  { question: "What is a database join?", answer: "Combines records from two or more tables based on a related column, returning a consolidated dataset.", category: "Technical" },
  { question: "Explain the difference between JavaScript and HTML.", answer: "HTML provides the skeleton and elements of web pages. JavaScript provides the dynamic programming logic, APIs, and animations.", category: "Technical" },
  { question: "What is a SQL constraint?", answer: "Rules applied to columns (e.g. NOT NULL, UNIQUE, CHECK, FOREIGN KEY) to enforce database data integrity.", category: "Technical" },
  { question: "What is git and how does it version control?", answer: "A distributed version control system tracking file changes, supporting parallel branch merging, and backing up repositories.", category: "Technical" },
  { question: "Explain bubble sort.", answer: "A simple sorting algorithm that repeatedly steps through the list, compares adjacent elements, and swaps them if in wrong order. Time is O(N^2).", category: "Coding" },
  { question: "What is cloud storage?", answer: "Data storage service hosted in cloud datacenters (e.g. AWS S3) accessible over APIs, removing local hard drive dependencies.", category: "Technical" },
  { question: "Explain responsive web design.", answer: "Creating layouts that automatically resize and adapt to different screen dimensions (mobile, tablet, desktop) using CSS grid/flexbox.", category: "Technical" },
  { question: "What is a software sprint?", answer: "A set period of time (typically 2 weeks) during which specific work must be completed and made ready for review.", category: "Technical" },
  { question: "Explain exception propagation.", answer: "When an exception is thrown and not caught in the current method, it is passed up the call stack to the calling method.", category: "Technical" },
  { question: "What is a database view?", answer: "A virtual table based on the result-set of an SQL query. Accesses complex tables without exposing underlying schemas.", category: "Technical" },
  { question: "Why Accenture?", answer: "Highlight their focus on consulting innovations, training pipelines, inclusive culture, and working on global client transformations.", category: "HR" },
  { question: "Describe a project you delivered in a team.", answer: "Detail the task, your personal coding contributions, how you sync-ed code using git, and final project outcomes.", category: "HR" },
  { question: "How do you handle difficult stakeholders?", answer: "Listen to requirements, present technical trade-offs transparently, and find data-driven compromises that fit user needs.", category: "HR" },
  { question: "What is your approach to learning new technologies?", answer: "Read documentation, complete standard tutorials, write code in sandboxes, and analyze stackoverflow discussions.", category: "HR" },
  { question: "Describe a time you failed to meet a deadline.", answer: "Explain what caused the delay, how you communicated updates, delivered the final output, and what you did to prevent it in the future.", category: "HR" }
];
